// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

type User struct {
	UserID    string
	FirstName string
	LastName  string
	Email     string
	Phone     string
	Age       int16
	Status    string
}
