// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/google/uuid"
)

type User struct {
	UserID    uuid.UUID
	FirstName string
	LastName  string
	Email     string
	Phone     string
	Age       int16
	Status    string
}
