// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"

	"github.com/google/uuid"
)

type Instrument struct {
	ID             uuid.UUID
	Symbol         string
	Name           string
	InstrumentType string
	Exchange       string
	LastPrice      string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type User struct {
	UserID    uuid.UUID
	FirstName string
	LastName  string
	Email     string
	Phone     string
	Age       int16
	Status    string
}
