// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :one
INSERT INTO USERS (USER_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE, AGE, STATUS)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING user_id, first_name, last_name, email, phone, age, status
`

type CreateUserParams struct {
	UserID    string
	FirstName string
	LastName  string
	Email     string
	Phone     string
	Age       int16
	Status    string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.UserID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Phone,
		arg.Age,
		arg.Status,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.Age,
		&i.Status,
	)
	return i, err
}

const deleteUserByID = `-- name: DeleteUserByID :exec
DELETE FROM USERS WHERE USER_ID = $1
`

func (q *Queries) DeleteUserByID(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteUserByID, userID)
	return err
}

const findUserById = `-- name: FindUserById :one
SELECT user_id, first_name, last_name, email, phone, age, status FROM USERS WHERE USER_ID = $1 LIMIT 1
`

func (q *Queries) FindUserById(ctx context.Context, userID string) (User, error) {
	row := q.db.QueryRowContext(ctx, findUserById, userID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.Age,
		&i.Status,
	)
	return i, err
}

const listAllUsers = `-- name: ListAllUsers :many
SELECT user_id, first_name, last_name, email, phone, age, status FROM USERS
`

func (q *Queries) ListAllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.UserID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Phone,
			&i.Age,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    FIRST_NAME = COALESCE($1, FIRST_NAME),
    LAST_NAME  = COALESCE($2, LAST_NAME),
    EMAIL      = COALESCE($3, EMAIL),
    PHONE      = COALESCE($4, PHONE),
    AGE        = COALESCE($5, AGE),
    STATUS     = COALESCE($6, STATUS)
WHERE user_id = $7
RETURNING user_id, first_name, last_name, email, phone, age, status
`

type UpdateUserParams struct {
	FirstName sql.NullString
	LastName  sql.NullString
	Email     sql.NullString
	Phone     sql.NullString
	Age       sql.NullInt16
	Status    sql.NullString
	UserID    string
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Phone,
		arg.Age,
		arg.Status,
		arg.UserID,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.Age,
		&i.Status,
	)
	return i, err
}
