CREATE TABLE IF NOT EXISTS USERS (
  USER_ID UUID PRIMARY KEY,
  FIRST_NAME VARCHAR(100) NOT NULL,
  LAST_NAME VARCHAR(100) NOT NULL,
  EMAIL TEXT UNIQUE NOT NULL,  
  PHONE TEXT NOT NULL,  
  AGE SMALLINT NOT NULL,
  STATUS TEXT NOT NULL
);