CREATE TABLE IF NOT EXISTS INSTRUMENTS (
    ID UUID PRIMARY KEY,
    SYMBOL VARCHAR(20) NOT NULL UNIQUE,
    NAME VARCHAR(100) NOT NULL,
    INSTRUMENT_TYPE VARCHAR(20) NOT NULL,
    EXCHANGE VARCHAR(20) NOT NULL,
    LAST_PRICE NUMERIC(18, 6) DEFAULT 0 NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT NOW() NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT NOW() NOT NULL
);